## Requiremnts

To clearly make the distinction between pandas and polars dataframes, we import the modules without aliasing in this notebook.

In [1]:
import pandas as pd
import polars as pl
import numpy as np

In [2]:
print(f'pandas {pd.__version__}')
print(f'polars {pl.__version__}')

pandas 3.1.0
polars 2.1.0

Note that benchmark numbers may differ across versions.

## Creating dataframes

In order to do some performance tests, we create some dataframes with a substantial amount of data.  The pandas dataframe will be assigned to the variable `df`, the polars dataframe in `cf`.

In [3]:
nr_rows = 20_000_000
data = {
    'A': np.random.uniform(0.0, 1.0, size=nr_rows),
    'B': np.random.uniform(0.0, 1.0, size=nr_rows),
    'C': np.random.uniform(0.0, 1.0, size=nr_rows),
}

In [4]:
df_pd = pd.DataFrame(data)

The polars dataframe is created in exactly the same way.

In [5]:
df_pl = pl.DataFrame(data)

It is interesting to check the datatypes used in the pandas and the polars dataframe, they are identical.

In [6]:
df_pd.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000000 entries, 0 to 19999999
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   A       float64
 1   B       float64
 2   C       float64
dtypes: float64(3)
memory usage: 457.8 MB

In [7]:
df_pl.describe()

shape: (9, 4)
┌────────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ A         ┆ B         ┆ C         │
│ ---        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 2e7       ┆ 2e7       ┆ 2e7       │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 0.499909  ┆ 0.499995  ┆ 0.500109  │
│ std        ┆ 0.288625  ┆ 0.28866   ┆ 0.288668  │
│ min        ┆ 4.3215e-8 ┆ 1.8517e-8 ┆ 5.3631e-8 │
│ 25%        ┆ 0.249921  ┆ 0.250068  ┆ 0.250138  │
│ 50%        ┆ 0.499898  ┆ 0.500051  ┆ 0.500264  │
│ 75%        ┆ 0.749928  ┆ 0.749946  ┆ 0.750135  │
│ max        ┆ 1.0       ┆ 1.0       ┆ 1.0       │
└────────────┴───────────┴───────────┴───────────┘

In [8]:
df_pl.estimated_size('mb')

457.763671875

The size of the dataframes is almost identical.

## Applying functions

We can time the difference between the pandas and polars when computing the columnwise average.

In [9]:
%timeit df_pd.A.mean()

42.6 ms ± 3.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [10]:
%timeit df_pl['A'].mean()

19.4 ms ± 2.96 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

It is clear that on average the computation on a polars dataframe is a factor of 3 faster.

Computing the rowwise average is substantially slower due to the data structure used to represent the dataframe.

In [11]:
%timeit df_pd.mean(axis=1)

507 ms ± 27.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]:
%timeit df_pl.select(pl.mean_horizontal(pl.all()).alias("mean"))

433 ms ± 69.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Again, polars outperforms the pandas implementation, although only by a factor of 2.

## Creating new columns

We can create a new column in a dataframe using an arithmetic expression on other columns.

In [13]:
%timeit df_pd['D'] = 2.1*df_pd.A + 3.5*df_pd.B

219 ms ± 115 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [14]:
%timeit df_pl.select((2.1*pl.col('A') + 3.5*pl.col('B').alias('D')))

96.7 ms ± 7.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Again, the polars dataframe outperformns the pandas version by a substantial factor.

## Categorical data

We can introduce a column that contains categorical data by using the `cut` function.  In this case, we bin column A, using 5 categories.  First we time the operation without storing the resulting values, then we store them in a new column, `'label'` for further testing.

In [15]:
%timeit pd.cut(df_pd.A, [0.0, 0.2, 0.4, 0.6, 0.8, 1.0], ['c1', 'c2', 'c3', 'c4', 'c5'])

762 ms ± 71.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [16]:
%timeit df_pl.select(pl.col('A').bin_intervals([0.2, 0.4, 0.6, 0.8, ], labels=['c1', 'c2', 'c3', 'c4', 'c5']))

707 ms ± 25.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Interestingly, the `cut` operation is less efficient for polars.

In [17]:
df_pd['label'] = pd.cut(df_pd.A, [0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
                        labels=['c1', 'c2', 'c3', 'c4', 'c5'])

In [18]:
df_pl = df_pl.select(
    pl.all(),
    pl.col('A') \
       .bin_intervals([0.2, 0.4, 0.6, 0.8, ],
                      labels=['c1', 'c2', 'c3', 'c4', 'c5']) \
       .alias('label')
)

## Group-by

Group-by operations are the bread and butter of data science, so we can check the performance using the column of categorical data we just added to the dataframes.

In [19]:
%timeit df_pd[['label', 'A']].groupby('label', observed=False).mean()

221 ms ± 29.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [20]:
%timeit df_pl['label', 'A'].group_by('label').mean()

35.4 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

## Pivots

In [21]:
pd.pivot_table(
    df_pd,
    index='label',
    values=['A', 'B', 'C'],
    aggfunc='mean',
    observed=False
)

              A         B         C
label
c1     0.100038  0.499972  0.500300
c2     0.299995  0.500117  0.500227
c3     0.500060  0.499767  0.500133
c4     0.700047  0.500069  0.500065
c5     0.899979  0.500051  0.499821

In [22]:
df_pl.group_by('label').agg(
    pl.col('A', 'B', 'C').mean()
)

shape: (5, 4)
┌───────┬──────────┬──────────┬──────────┐
│ label ┆ A        ┆ B        ┆ C        │
│ ---   ┆ ---      ┆ ---      ┆ ---      │
│ enum  ┆ f64      ┆ f64      ┆ f64      │
╞═══════╪══════════╪══════════╪══════════╡
│ c1    ┆ 0.100038 ┆ 0.499972 ┆ 0.5003   │
│ c3    ┆ 0.50006  ┆ 0.499767 ┆ 0.500133 │
│ c5    ┆ 0.899979 ┆ 0.500051 ┆ 0.499821 │
│ c4    ┆ 0.700047 ┆ 0.500069 ┆ 0.500065 │
│ c2    ┆ 0.299995 ┆ 0.500117 ┆ 0.500227 │
└───────┴──────────┴──────────┴──────────┘

Unfortunately, for pivot tables, the `polars` implementation is quite different from the pandas implementation.  However, the pivot operation on the pandas dataframe can be implemented using a simple `groupby`, folloed by applying `mean`.

In [23]:
df_pl['label', 'A', 'B', 'C'].group_by('label', maintain_order=True).mean()

shape: (5, 4)
┌───────┬──────────┬──────────┬──────────┐
│ label ┆ A        ┆ B        ┆ C        │
│ ---   ┆ ---      ┆ ---      ┆ ---      │
│ enum  ┆ f64      ┆ f64      ┆ f64      │
╞═══════╪══════════╪══════════╪══════════╡
│ c1    ┆ 0.100038 ┆ 0.499972 ┆ 0.5003   │
│ c3    ┆ 0.50006  ┆ 0.499767 ┆ 0.500133 │
│ c5    ┆ 0.899979 ┆ 0.500051 ┆ 0.499821 │
│ c4    ┆ 0.700047 ┆ 0.500069 ┆ 0.500065 │
│ c2    ┆ 0.299995 ┆ 0.500117 ┆ 0.500227 │
└───────┴──────────┴──────────┴──────────┘

In [24]:
%timeit pd.pivot_table(df_pd, index='label', \
                       values=['A', 'B', 'C'], \
                       aggfunc='mean', \
                       observed=False)

339 ms ± 21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [25]:
%timeit df_pl['label', 'A', 'B', 'C'].group_by('label').mean()

48.2 ms ± 3.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

## Conclusion

Polars outperforms pandas on most operations, though not all.  However, pandas has more features and it is easier to find examples and help.